export const PAGE_LOGIN = '/login'
export const PAGE_HOME = '/'

export const PAGE_ADD_MEMBER = '/addMember'
export const PAGE_CLUB_SETTINGS = '/clubSettings'
export const PAGE_CREATE_CLUB = '/createClub'
export const PAGE_REGISTRATION_SUCCESS = '/registerSuccess'
export const PAGE_REGISTRATION = '/register'
export const PAGE_ACTIVITY = '/createActivity'
export const PAGE_CREATE_TASK = '/createTask'
export const PAGE_CREATE_EVENT = '/createEvent'
export const PAGE_CALENDAR = '/calendar'
export const PAGE_GANTT = '/gantt'
export const PAGE_UPDATE_TASK = '/updateTask'
export const PAGE_UPDATE_EVENT = '/updateEvent'